Controllers/BoardController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using IronPen.Models;
using Microsoft.AspNet.Identity;
using Newtonsoft.Json;

namespace IronPen.Controllers
{
    public class BoardController : Controller
    {
        private IronPenEntities db = new IronPenEntities();

        [Authorize]
        // GET: Board
        public ActionResult Index(string p)
        {
            var users = db.AspNetUsers.Select(c => c.Email);
            ViewBag.users = users;
            var currentUserId = User.Identity.GetUserId();
            var userName = db.AspNetUsers.Where(c => c.Id == currentUserId).FirstOrDefault().UserName;
            ViewBag.userName = userName;
            var found = db.Groups.Where(c => c.Url == p).Count();
            if (found != 0)
            {
                var groupId = db.Groups.Where(c => c.Url == p).FirstOrDefault().Id;
                var canJoin =
                    db.GroupVsUsers.Where(c => c.GroupId == groupId)
                        .Where(c => c.UserId == currentUserId)
                        .Where(c => c.Status == 1).Where(c => c.Group.Status == 1).Count();
                if (canJoin == 0)
                {
                    TempData["errorMessage"] = "You are not allowed to join this Session";
                    return Redirect("~/Groups/");
                }


            }
            else
            {
                TempData["errorMessage"] = "This Session doesn`t exist";
                return Redirect("~/Groups/");
            }
            ViewData["IsNewGroup"] = false;
            ViewData["GroupName"] = p;
            ViewBag.GroupName = p;
            //allowed users in the Session
            var onlineUsers = db.GroupVsUsers.Where(c => c.Group.Url == p).Where(c => c.Status == 1);
            ViewBag.onlineUsers = onlineUsers;
            var OwnerId =
                db.GroupVsUsers.Where(c => c.Group.Url == p).Where(c => c.Role == 1)
                    .FirstOrDefault().UserId;
            var FeaturedUserId =
                db.GroupVsUsers.Where(c => c.Group.Url == p).Where(c => c.Feature == 1).Where(c=>c.UserId==currentUserId)
                    .Count();
            if (OwnerId == currentUserId)
            {
                ViewBag.Owner = 1;
            }
            else
            {
                ViewBag.Owner = 0;

            }
            if (FeaturedUserId == 1)
            {
                ViewBag.FeatureAccess = 1;
            }
            else
            {
                ViewBag.FeatureAccess = 0;

            }
            return View();
        }

        [Authorize]
        public ActionResult invite(List<String> email, string p)
        {
            var currentUser = User.Identity.GetUserId();
            var group = db.Groups.Where(c => c.Url == p).FirstOrDefault();

            foreach (var item in email)
            {
                var userInvited = db.AspNetUsers.Where(c => c.UserName == item).FirstOrDefault();
                var alreadyInvited =
                    db.GroupVsUsers.Where(c => c.UserId == userInvited.Id).Where(c => c.GroupId == group.Id).Count();
                if (alreadyInvited == 0)
                {
                    GroupVsUser groupVsUser = new GroupVsUser();
                    groupVsUser.UserId = userInvited.Id;
                    groupVsUser.GroupId = group.Id;
                    groupVsUser.Status = 0; //Invited user
                    groupVsUser.Role = 2;
                    db.GroupVsUsers.Add(groupVsUser);
                    db.SaveChanges();
                    Notification notification = new Notification();
                    notification.SenderId = currentUser;
                    notification.ReciverId = userInvited.Id;
                    notification.Time = DateTime.Now;
                    notification.Status = 0;
                    notification.Description = "You are invited to join " + group.GroupName;
                    notification.GroupId = group.Id;
                    db.Notifications.Add(notification);
                    db.SaveChanges();
                }
                else
                {
                    return Json(new {error = "This User is Already invited"});

                }

            }

            return Json(new {});
        }

        [Authorize]
        public ActionResult blockUser(string userId, string p)
        {
            var groupId = db.Groups.Where(c => c.Url == p).FirstOrDefault().Id;
            var blockedUser = db.AspNetUsers.Where(c => c.Id == userId).FirstOrDefault();
            var userData = db.GroupVsUsers.Where(c => c.GroupId == groupId).Where(c => c.UserId == blockedUser.Id).FirstOrDefault();
            var x = userData.Status;
            var result = "";
            if (x == 1)
            {
                userData.Status = 2;
                result = "UnBlock";
            }
            else
            {
                userData.Status = 1;
                result = "Block";
            }
            db.Entry(userData).State = EntityState.Modified;
            db.SaveChanges();
            return Json(new {success = result});
            

        }

        [Authorize]
        public ActionResult allowFeature(string userId, string p)
        {
            var groupId = db.Groups.Where(c => c.Url == p).FirstOrDefault().Id;
            var user = db.AspNetUsers.Where(c => c.Id == userId).FirstOrDefault();

            var userData=db.GroupVsUsers.Where(c => c.GroupId == groupId).Where(c => c.UserId == user.Id).FirstOrDefault();
            var x = userData.Feature;
            var result = "";
            if (x == 0)
            {
                userData.Feature = 1;
                result = "Disable";
            }
            else
            {
                userData.Feature = 0;
                result = "Allow";
            }
            db.Entry(userData).State = EntityState.Modified;
            db.SaveChanges();
            return Json(new {success = result});
        }

        public ActionResult saveImage(string base64,string p,string replay)
        {
            var groupId = db.Groups.Where(c => c.Url == p).FirstOrDefault().Id;
            base64 = base64.Replace("data:image/png;base64,", String.Empty);
            byte[] data = Convert.FromBase64String(base64);
            Image image;
            using (var stream = new MemoryStream(data, 0, data.Length))
            {
                image = Image.FromStream(stream);
                
            }
            Album imgAlbum = new Album();
            String unique = DateTime.Now.ToString("yyyyMMddHHmmssfff");
            var path = @"Content/Albums/" + p +"-"+ unique;
            var path2 = Server.MapPath("~/Content/Albums/" + p + "-" + unique);

            imgAlbum.ImageLink = path+".jpg";
            imgAlbum.FileLink = path+".txt";
            imgAlbum.GroupId = groupId;
            db.Albums.Add(imgAlbum);
            db.SaveChanges();
            image.Save(path2 + ".jpg", System.Drawing.Imaging.ImageFormat.Png);
            System.IO.File.WriteAllText(path2 + ".txt", replay);

            return Json(new {});
        }

    }
}

Views/Board/Index.cshtml
@using Microsoft.AspNet.Identity
@{
    ViewBag.Title = "Home Page";
    Layout = "~/Views/Shared/_Layout.cshtml";

}
<link href="~/Content/selectize.css" rel="stylesheet"/>
<script src="~/Scripts/saver.js"></script>
<style type="text/css">
    #container {
        position: relative;
        overflow: auto;
        scrollbar-base-color: #ffeaff;
        scrollbar-base-color: #ffeaff;
    }

    #whiteBoard {
        border: 1px dashed #CCCCCC;
        margin: 5px;
        border-style: dotted;
        border-width: 1px;
        background-color: #FFFFFF;
        vertical-align: top;
    }

    #imageTemp {
        position: absolute;
        top: 1px;
        left: 1px;
        margin: 5px;
    }

    #imageTempt {
        position: absolute;
        top: 1px;
        left: 1px;
        margin: 5px;
    }

    .ui-widget-overlay {
        opacity: .70;
        filter: Alpha(Opacity=70);
    }
</style>
<table width="100%" id="tableWhiteBoard">
    <tr>
        <td style="width: 80%">
            <table style="vertical-align: top; width: 100%;" cellpadding="0" cellspacing="0">
                @if (ViewBag.Owner == 1 || ViewBag.FeatureAccess==1)
                {
                    <tr>
                        <td>
                            <img id="imgline" style="border-color: Gray; border-style: dashed; width: 32px; height: 32px"
                                 src="/images/line_dim.png" onclick="SelectTool('line'); return false;" />
                            <img id="imgpencil" style="border-color: Gray; border-style: dashed; width: 32px;
                                                                                                                                                                                                                                                                                            height: 32px" src="/images/pencil_dim.png" onclick="SelectTool('pencil'); return false;" />
                            <img id="imgrect" style="border-color: Gray; border-style: dashed; width: 32px; height: 32px"
                                 src="/images/rect_dim.png" onclick="SelectTool('rect'); return false;" />
                            <img id="imgtext" style="border-color: Gray; border-style: dashed; width: 32px; height: 32px"
                                 src="/images/text_dim.png" onclick="SelectTool('text'); return false;" />
                            <img id="imgerase" style="border-color: Gray; border-style: dashed; width: 32px;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           height: 32px" src="/images/erase_dim.png" onclick="SelectTool('erase'); return false;" />
                            <img id="imgSave" style="border: 0; border-style: dashed; width: 32px; height: 32px"
                                 src="/images/save.png" />
                            <span class="pull-right">
                                <div class="form-group form-inline">
                                    <select type="text" id="emails" name="emails[]" class="form-inline" multiple="multiple">
                                        @foreach (var item in ViewBag.users)
                                        {
                                            <option value="@item">@item</option>
                                        }
                                    </select>
                                    <button class="btn btn-success" id="invite">Invite</button>
                                </div>

                            </span>
                        </td>
                    </tr>

                }
                <tr>
                    <td style="vertical-align: top;">
                        <div id="container" style="width: 100%; height: 842px">
                            <canvas id="whiteBoard"></canvas>
                            <div id="status">
                            </div>
                        </div>
                    </td>
                </tr>
            </table>
        </td>
        <td valign="top">

            <div style="margin-top: 38px;">
                <div class="well well-sm">
                    <ul class="" id="onlineUsers">
                        @foreach (var item in ViewBag.onlineUsers)
                        {
                            if(item.AspNetUser.Id!=User.Identity.GetUserId()){
                            <li>@item.AspNetUser.UserName</li>
                            if (ViewBag.Owner == 1)
                            {
                                if (item.Status==1)
                                {
                                    <button class="btn btn-xs btn-danger blockUser" value="@item.AspNetUser.Id"> Block </button>

                                }
                                else
                                {
                                    <button class="btn btn-xs btn-danger blockUser" value="@item.AspNetUser.Id"> UnBlock </button>

                                }
                                if (item.Feature == 0)
                                {
                                    <button class="btn btn-xs btn-default allowFeature" value="@item.AspNetUser.Id"> Allow </button>

                                }
                                else
                                {
                                    <button class="btn btn-xs btn-default allowFeature" value="@item.AspNetUser.Id"> Disable </button>

                                }
                            }
                            }
                        }
                    </ul>
                </div>
                
                <div class="text-center" align="center"><h4>Chat</h4>
                </div>
                <div id="divMessage" style="height: 150px; width: 220px; padding: 2px; border: 2px; solid: black; background-color: white;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  overflow-y: scroll;">
                </div>
                <textarea rows="2" cols="25" id="txtMessage" class="form-control" style="width: 205px; margin-top: 5px"></textarea>
                <div align="center">
                    <input type="button" class="btn btn-primary btn-md" id="btnSend" style="margin: 5px auto;" value="Send"/>
                </div>

                <div id="divStatus">
                </div>
            </div>

        </td>
    </tr>
</table>
<input type="hidden" id="sessinId" value="@Session.SessionID" />
<input type="hidden" id="groupName" value="@ViewData["GroupName"]" />
<script type="text/javascript">
    if (Modernizr.canvas) {

    } else {
        document.getElementById('tableWhiteBoard').style.display="none";
        document.write( " Please use a browser which support HTML5. IE8+, Chrome or Firefox 4.0 +.  <br/><br/>@DateTime.Now.Year - Online Whiteboard using HTML5 and SignalR by Alvin George ");
        alert("This browser does not support HTML5. Try with higher version.");
    }

</script>




<input type="hidden" id="userName" value="@ViewData["UserName"]"/>
<input type="hidden" id="name" value="@ViewBag.userName" class="text ui-widget-content ui-corner-all" maxlength="25" />

<script src="~/Content/Site/js/jquery-2.1.1.js"></script>
<script src="~/Scripts/whiteboard_1.js" type="text/javascript"></script>

<script>
    var userNamee = "@ViewBag.userName";
    $().ready(function() {
        $('#tableWhiteBoard').click(function() {

        });

        setTimeout(function() {
            $("#sideBarCollapse").click();

        }, 100);
    });

    //invite User
    $("#invite").click(function() {
        var x = $("#emails").val();
        $.ajax({
            url: "@Url.Action("invite", "Board")",
            type: "POST",
            data: { email: x,p: "@Request["p"].ToString()"},
            dataType: "html",
            traditional: true,
            success: function (dataa) {
                var data = $.parseJSON(dataa);
                if (data.error !=null){
                    alert(data.error);
                }
            },
            error: function (dataa) {

            }
        });

    });

    //Block user
    $(".blockUser").click(function() {
        var x = this.value;
        var y = $(this)[0];

        $.ajax({
            url: "@Url.Action("blockUser", "Board")",
            type: "POST",
            data: { userId: x,p: "@Request["p"].ToString()"},
            dataType: "html",
            traditional: true,
            success: function (dataa) {

                var data = $.parseJSON(dataa);
                if (data.success != null) {
                    y.innerText = data.success;
                }
                if (data.error !=null){
                    alert(data.error);
                }
            },
            error: function (dataa) {

            }
        });

    });
    //Allow Feature
    $(".allowFeature").click(function() {
        var x = this.value;
        var y = $(this)[0];
        $.ajax({
            url: "@Url.Action("allowFeature", "Board")",
            type: "POST",
            data: { userId: x,p: "@Request["p"].ToString()"},
            dataType: "html",
            traditional: true,
            success: function (dataa) {
                var data = $.parseJSON(dataa);
                if (data.success != null) {
                    y.innerText = data.success;
                }
                if (data.error !=null){
                    alert(data.error);
                }
            },
            error: function (dataa) {

            }
        });
    });
</script>

<script>
    $().ready(function() {
        $('#emails').selectize({
            persist: false,
            createOnBlur: true,
            create: true,
            total: 1
        });
    });

</script>
<script>
    $("#imgSave").click(function () {
        var filename = 'json_file'; // name of file
        var text = ""; // content of file
        text = JSON.stringify(objects_array_file); // convert objects to plain text
        
        var img = canvaso.toDataURL("image/png");
        $.ajax({
            url: "@Url.Action("saveImage", "Board")",
            type: "POST",
        data: { base64: img,p: "@Request["p"].ToString()",replay:text},
        dataType: "html",
        traditional: true,
        success: function (dataa) {
        },
        error: function (dataa) {

        }
    });
    });
</script>